version: '3.2'
name: HARALD
services:
  db:
    image: postgres
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust

  node-1:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 8080:80
    environment:
      # Modify your config files (dev.exs and test.exs) so that the password and hostname can be overridden
      # when environment variables are set:
      # password: System.get_env("DB_PASS", "postgres"),
      # hostname: System.get_env("DB_HOST", "localhost"),
      - DB_PASS=
      - DB_HOST=db
      - ERLANG_COOKIE=HARALD
      - NODE_NAME=node-1
    depends_on:
      - db
    command:
      - ./run.sh

  node-2:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 8081:80
    environment:
      # Modify your config files (dev.exs and test.exs) so that the password and hostname can be overridden
      # when environment variables are set:
      # password: System.get_env("DB_PASS", "postgres"),
      # hostname: System.get_env("DB_HOST", "localhost"),
      - DB_PASS=
      - DB_HOST=db
      - ERLANG_COOKIE=HARALD
      - NODE_NAME=node-2
    depends_on:
      - db
    command:
      - ./run.sh
