name: HARALD
services:
  db:
    container_name: db
    image: postgres:17
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust

  lb:
    container_name: lb
    build: ./load-balancer/
    ports:
      - 8080:80
      - 9000:9000
    volumes:
      # bind haproxy.cfg to the container
      - type: bind
        source: ./load-balancer/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - node-1
      - node-2
  
  dashboard:
    container_name: dashboard
    image: grafana/grafana-oss:11.6.0
    ports:
      - 3000:3000
    volumes:
      - ./dashboard:/var/lib/grafana
    depends_on:
      - metrics
  
  metrics:
    container_name: metrics
    image: prom/prometheus:v2.53.4
    ports:
      - 9090:9090
    volumes:
      # bind prometheus.yml to the container
      - type: bind
        source: ./admin/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    depends_on:
      - lb

  node-1:
    container_name: node-1
    build: ./website-application/
    volumes:
      - type: bind
        source: ./website-application/
        target: /app
    # ports:
    #   - 8081:80
    environment:
      # Modify your config files (dev.exs and test.exs) so that the password and hostname can be overridden
      # when environment variables are set:
      # password: System.get_env("DB_PASS", "postgres"),
      # hostname: System.get_env("DB_HOST", "localhost"),
      - DB_PASS=
      - DB_HOST=db
      - ERLANG_COOKIE=HARALD
      - NODE_NAME=node-1
    depends_on:
      - db
    command:
      - ./run.sh
    # deploy:
    #   replicas: 2

  node-2:
    container_name: node-2
    build: ./website-application/
    volumes:
      - type: bind
        source: ./website-application/
        target: /app
    # ports:
    #   - 8081:80
    environment:
      # Modify your config files (dev.exs and test.exs) so that the password and hostname can be overridden
      # when environment variables are set:
      # password: System.get_env("DB_PASS", "postgres"),
      # hostname: System.get_env("DB_HOST", "localhost"),
      - DB_PASS=
      - DB_HOST=db
      - ERLANG_COOKIE=HARALD
      - NODE_NAME=node-2
    depends_on:
      - db
    command: ["./run.sh"]
