# my global config
global:
  scrape_interval: 1s
  evaluation_interval: 10s
  body_size_limit: 15MB
  sample_limit: 1500
  target_limit: 30
  label_limit: 30
  label_name_length_limit: 200
  label_value_length_limit: 200
  query_log_file: query.log
  # scrape_timeout is set to the global default (10s).


runtime:
  gogc: 42

scrape_configs:
  - job_name: prometheus

    honor_labels: true
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
        labels:
          my: label
          your: label

    tls_config:
      min_version: TLS10

  - job_name: 'load-balancer-metrics'
    static_configs:
      - targets: ['lb:8405']


storage:
  tsdb:
    out_of_order_time_window: 30m
