# my global config
global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 5s
  body_size_limit: 15MB
  sample_limit: 0
  target_limit: 0
  label_limit: 0
  label_name_length_limit: 0
  label_value_length_limit: 0
  query_log_file: query.log
  # scrape_timeout is set to the global default (10s).


runtime:
  gogc: 42

scrape_configs:
  - job_name: Prometheus

    honor_labels: true
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

    tls_config:
      min_version: TLS10

  - job_name: 'HAProxy'
    static_configs:
      - targets: ['192.168.0.105:8405']
    params: 
      extra-counters: ["on"]

  - job_name: Postgres
    static_configs:
      - targets: ["192.168.0.102:9187"]

  - job_name: Node
    static_configs:
      - targets: ["192.168.0.101:80", "192.168.0.100:80"]

storage:
  tsdb:
    out_of_order_time_window: 30m
